Medium.destroy_all
Host.destroy_all
Guest.destroy_all

### JOE ROGAN EXPERIENCE
# @joe = Host.create!(name: "Joe Rogan Experience", description: "Joe Rogan interviews a wide array of guests including actors, comedians, politicians, and mixed martial arts athletes and commentators")
@melissa = Guest.create!(name: "Melissa Chen", description: "Singaporean journalist and activist. She is an author for Spectator USA and co-founder of Ideas Beyond Borders.", url: "<blockquote class='twitter-tweet'><p lang='en' dir='ltr'>Do they do Ugly Christmas Speedos instead of sweaters here?<br><br>Merry Christmas 🎄 to you all from Down Under! <a href='https://t.co/nh9uQb6lWD'>pic.twitter.com/nh9uQb6lWD</a></p>&mdash; Melissa Chen (@MsMelChen) <a href='https://twitter.com/MsMelChen/status/1077241644620013570?ref_src=twsrc%5Etfw'>December 24, 2018</a></blockquote> <script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>", tags: "Atheist")
@melissa.media.create!(name: "Joe Rogan Experience #1427 - Melissa Chen", description: "They discuss Singapore, China, religion, etc.", url: "<iframe src='https://open.spotify.com/embed-podcast/episode/1vVnxqzgdVO385p7DaEvFI' width='100%' height='232' frameborder='0' allowtransparency='true' allow='encrypted-media'></iframe>", guest_id: @melissa.id)

@bret = Guest.create!(name: "Bret Weinstein & Heather Heying", description: "Evolutionary biologists and hosts of the Dark Horse Podcast.", url: "<blockquote class='twitter-tweet'><p lang='en' dir='ltr'>Heather Heying and Bret Weinstein tell their Evergreen State story <a href='https://t.co/X8U9IUVtiO'>https://t.co/X8U9IUVtiO</a> <a href='https://t.co/Ti1d0ez21b'>pic.twitter.com/Ti1d0ez21b</a></p>&mdash; Jerry Coyne (@Evolutionistrue) <a href='https://twitter.com/Evolutionistrue/status/942462176152997889?ref_src=twsrc%5Etfw'>December 17, 2017</a></blockquote> <script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>", tags: "Atheist, Liberal")
@bret.media.create!(name: "Joe Rogan Experience #1081 - Bret Weinstein & Heather Heying", description: "They discuss their departure from Evergreen State College, evolutionary biology, and politics.", url: "<iframe src='https://open.spotify.com/embed-podcast/episode/4pmejCvCxZDK1JVgNkm2Y5' width='100%' height='232' frameborder='0' allowtransparency='true' allow='encrypted-media'></iframe>", guest_id: @bret.id)
@bret.media.create!(name: "Real Time with Bill Maher", description: "Evolutionary biologists Heather Heying and Bret Weinstein join Bill Maher to discuss the nature and possible origins of the SARS-CoV-2 coronavirus.", url: "<iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/ZMGWLLDSA3c' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>")

@murray = Guest.create!(name: "Douglas Murray", description: "Author, journalist, and political commentator. Associate editor of The Spectator UK. His most recent books are 'The Madness of Crowds: Gender, Race and Identity' and 'The Strange Death of Europe'", url: "<blockquote class='twitter-tweet'><p lang='und' dir='ltr'><a href='https://t.co/OuQssQ5a6Z'>pic.twitter.com/OuQssQ5a6Z</a></p>&mdash; Douglas Murray (@DouglasKMurray) <a href='https://twitter.com/DouglasKMurray/status/1188983573929496576?ref_src=twsrc%5Etfw'>October 29, 2019</a></blockquote> <script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>", tags: "Atheist, Gay, Conservative")
@murray.media.create!(name: "Joe Rogan Experience #1084 - Douglas Murray", description: "They discuss American culture, geopolitics, and religion.", url: "<iframe src='https://open.spotify.com/embed-podcast/episode/01ZHPv93wNv2mB7PzfWUvW' width='100%' height='232' frameborder='0' allowtransparency='true' allow='encrypted-media'></iframe>", guest_id: @murray.id)

### FEMSPLAINERS

# @femsplainers = Host.create!(name: "The Femsplainers Podcast", description: "Weekly girl’s night out with hosts Danielle Crittenden & Christina Hoff Sommers, plus some of the most fascinating and fabulous women on the planet. We dish on everything from #metoo and sex to, well, doing the dishes. No topic is off-limits - unless it’s boring.")
@ayaan = Guest.create!(name: "Ayaan Hirsi Ali", description: "AHA Foundation Founder, women’s rights activist, champion of free speech, best-selling author, former Dutch parliament member.", url: "<blockquote class='twitter-tweet'><p lang='en' dir='ltr'><a href='https://twitter.com/hashtag/WisdomWednesday?src=hash&amp;ref_src=twsrc%5Etfw'>#WisdomWednesday</a> a quote from our Founder, Ayaan Hirsi Ali. We must stand up against violence against women in the U.S.! <a href='https://t.co/iZlz6owrGp'>pic.twitter.com/iZlz6owrGp</a></p>&mdash; AHA Foundation (@AHAFoundation) <a href='https://twitter.com/AHAFoundation/status/1184475248776876033?ref_src=twsrc%5Etfw'>October 16, 2019</a></blockquote> <script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>", tags: "Atheist")
@ayaan.media.create!(name: "The Ayaan Hirsi Ali You DON'T Know", description: "An intimate girls' night out with the Femsplainers and the celebrated champion of Islamic women's rights. (She's also our BFF.)", url: "<iframe src='https://open.spotify.com/embed-podcast/episode/4fD1HEGafizrGDiPrSgxS2' width='100%' height='232' frameborder='0' allowtransparency='true' allow='encrypted-media'></iframe>", guest_id: @ayaan.id)
### SAM HARRIS

# @samharris = Host.create!(name: "Making Sense with Sam Harris", description: "Join Sam Harris - neuroscientist, philosopher, and best-selling author—as he explores some of the most important questions about the human mind, society, and current events.")
@ayaan.media.create!(name: "#50 — The Borders of Tolerance", description: "Sam Harris speaks with Ayaan Hirsi Ali about Islamism, the migrant crisis in Europe, and other topics.", url: "<iframe src='https://www.listennotes.com/embedded/e/7fc631ed7b4040049b280964dbdd78d7/' height='300px' width='100%' style='width: 1px; min-width: 100%;' frameborder='0' scrolling='no'></iframe>", guest_id: @ayaan.id)

@yasmine = Guest.create!(name: "Yasmine Mohammed", description: "Canadian human rights activist who advocates for the rights of women living within Islamic majority countries or under religious fundamentalism. Founder of Free Hearts Free Minds and author of 'Unveiled.'", url: "<blockquote class='twitter-tweet'><p lang='en' dir='ltr'>It’s finally here. I still can’t believe it.<br><br>Thank you to all of you who have supported me the past three years.<br><br>And a special thank you to <a href='https://twitter.com/Ayaan?ref_src=twsrc%5Etfw'>@Ayaan</a> <a href='https://twitter.com/SamHarrisOrg?ref_src=twsrc%5Etfw'>@SamHarrisOrg</a> <a href='https://twitter.com/MaajidNawaz?ref_src=twsrc%5Etfw'>@MaajidNawaz</a> and <a href='https://twitter.com/RichardDawkins?ref_src=twsrc%5Etfw'>@RichardDawkins</a> for providing such wonderful testimonials 💗 <a href='https://t.co/2qBSXv92f8'>pic.twitter.com/2qBSXv92f8</a></p>&mdash; Yasmine Mohammed ياسمين محمد 🦋 (@YasMohammedxx) <a href='https://twitter.com/YasMohammedxx/status/1171199840635645952?ref_src=twsrc%5Etfw'>September 9, 2019</a></blockquote> <script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>", tags: "Atheist, Liberal")
@yasmine.media.create!(name: "#175 — Leaving the Faith", description: "Sam Harris speaks with Yasmine Mohammed about her book 'Unveiled: How Western Liberals Empower Radical Islam.' They discuss her family background and indoctrination into conservative Islam, the double standard that Western liberals use when thinking about women in the Muslim community, the state of feminism in general, honor violence, the validity of criticizing other cultures, and many other topics.", url: "<iframe src='https://www.listennotes.com/embedded/e/d76f3a9c39714da29b56668df0a68f31/' height='300px' width='100%' style='width: 1px; min-width: 100%;' frameborder='0' scrolling='no'></iframe>", guest_id: @yasmine.id)
### BRIDGET PHETASY

# @phetasy = Host.create!(name: "Walk-Ins Welcome with Bridget Phetasy", description: "Bridget Phetasy admires grit and authenticity. On Walk-Ins Welcome, she talks about the beautiful failures and frightening successes of her own life and the lives of her guests. She doesn’t conduct interviews—she has conversations. Conversations with real people about the real struggle and will remind you that we can laugh in pain and cry in joy but there’s no greater mistake than hiding from it all. By embracing it all, and celebrating it with the stories she’ll bring listeners, she believes that our lowest moments can be the building blocks for our eventual fulfillment.")
@yasmine.media.create!(name: "Walk-Ins Welcome Podcast #53 - Yasmine Mohammed", description: "Yasmine shares her story of growing up in a fundamentalist Islamic home in Canada. They cover the escalation of rape culture, sexual harassment, the problems with celebrating the hijab, the indoctrination of attitudes towards girls and women in Muslim culture, and being called Islamophobic for criticizing a tool and system of oppression. They bond over shared traumatic experiences and discuss their belief that if you can use your own trauma to help others, it has not happened in vain.", url: "<iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/9NTqk-6hZ-I' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>", guest_id: @yasmine.id)

@doyle = Guest.create!(name: "Andrew Doyle", description: "English comedian, playwright, journalist, political satirist, creator of the fictitious character Titania McGrath", url: "<blockquote class='twitter-tweet'><p lang='en' dir='ltr'>Ever get the feeling someone’s looking over your shoulder? <a href='https://t.co/jcNNPUUuJu'>pic.twitter.com/jcNNPUUuJu</a></p>&mdash; Andrew Doyle (@andrewdoyle_com) <a href='https://twitter.com/andrewdoyle_com/status/1342048794393849863?ref_src=twsrc%5Etfw'>December 24, 2020</a></blockquote> <script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>", tags: "Gay, Liberal")
@doyle.media.create!(name: "Joe Rogan Experience #1423 - Andrew Doyle", description: "Discussion on cancel culture, woke culture, Titania McGrath, the Bible, and more", url: "<iframe src='https://open.spotify.com/embed-podcast/episode/1cOpuHraGD75nZImGTAsSL' width='100%' height='232' frameborder='0' allowtransparency='true' allow='encrypted-media'></iframe>", guest_id: @doyle.id)

@zaid = Guest.create!(name: "Zaid Jilani", description: "Investigative journalist and blogger", url: "<blockquote class='twitter-tweet'><p lang='en' dir='ltr'>Police shootings are rare and declining. Shootings and murders committed by criminal are more common and increasing. Yet the former gets so much ink and attention and the latter next to none because the media is obsessed with Narrative over truth. <a href='https://t.co/pc7ir2A32L'>https://t.co/pc7ir2A32L</a></p>&mdash; Zaid Jilani (@ZaidJilani) <a href='https://twitter.com/ZaidJilani/status/1385031952386990082?ref_src=twsrc%5Etfw'>April 22, 2021</a></blockquote> <script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>")
@zaid.media.create!(name: "Don't Let Yourself Be GASLIGHTED Into Tribal Politics", description: "On Rising, journalist Zaid Jilani explains how most people have more complex views on the issues than their party affiliation suggests.", url: "<iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/-ldxgtN6-rY' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>")
@zaid.media.create!(name: "Fact And Fiction On Anti-Asian Violence", description: "On Rising, Journalist, Zaid Jilani, discusses his new piece in Newsweek, 'We Can't Stop Anti-Asian Violence Until We're Honest About It'.", url: "<iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/AqZrqc87hFU' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>", tags: "race")
@coleman = Guest.create!(name: "Coleman Hughes", description: "Writer, podcaster and opinion columnist who specialises in issues related to race, public policy and applied ethics.", url: "<blockquote class='twitter-tweet'><p lang='en' dir='ltr'>It&#39;s such an honor to be named one of Forbes 30 under 30! I am genuinely so thankful for your support. Thank you for all the likes, comments, shares, listens, DM&#39;s, and subscriptions. This listing would not have been a reality without you. <a href='https://twitter.com/ForbesUnder30?ref_src=twsrc%5Etfw'>@ForbesUnder30</a> <a href='https://t.co/pzSBjSD53C'>https://t.co/pzSBjSD53C</a> <a href='https://t.co/W8SGTUYWRy'>pic.twitter.com/W8SGTUYWRy</a></p>&mdash; Coleman Hughes (@coldxman) <a href='https://twitter.com/coldxman/status/1334094183234093057?ref_src=twsrc%5Etfw'>December 2, 2020</a></blockquote> <script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>")
@coleman.media.create!(name: "The Empirical Problems with Systemic Racism", description: "What is the difference between individual, institutional, and systemic racism? What are the empirical problems with systemic racism?", url: "<iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/zOtVDwnFTzw' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>", tags: "race")
@coleman.media.create!(name: "Coleman Hughes on The Problem of Race with Glenn Loury", description: "This conversation is a big picture discussion of the problem of race in America today, the narratives that compete for space in the mainstream media and the path forward.", url: "<iframe width='560' height='315' src='https://www.youtube-nocookie.com/embed/tGLUk48u5l0' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>", tags: "race")
